Repository hack4impact-mcgill/MealCare, pull requests merged in 2020-03, with the labels that each got.

#9 Finished backend setup for postgres, fastapi, and tests
  backend/.gitignore
  backend/README.md
  backend/app/__init__.py
  backend/app/main/main.py
  backend/config.py
  backend/manage.py
  backend/requirements.txt
  backend/scripts/setup_db.py
  backend/tests/api/base_api_test.py
  backend/tests/api/test_main.py
  backend/tests/unit/test_database.py
Labels: enhancement

#13 Added Vendor entity and exposed route for adding vendors
  .gitignore
  backend/app/main/dbase.py
  backend/app/main/main.py
  backend/tests/api/test_main.py
Labels: enhancement

#3 Update Readme. Correct Robin Leman's name.
  README.md
Labels: documentation

#17 Added food entity in the database, exposed route for adding food, created test for adding food
  backend/app/main/dbase.py
  backend/app/main/main.py
  backend/tests/api/test_main.py
Labels: enhancement

#19 Conflict resolution for food entity
  backend/app/main/dbase.py
  backend/tests/api/test_main.py
Labels: bug
